
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: todolist
  username: postgres
  password: test

development:
    adapter: postgresql
    encoding: unicode
    pool: 5
    database: todolist
    username: postgres
    password: test
test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: todolist
  username: postgres
  password: test
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: todolist
  username: postgres
  password: test
